-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-08-23 00:37:22 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

/* Author: Janice Ivana
   Date: 23 August 2025
   Please to credit to the Author if using any of the work into your personal/work/study/research.
   Thanks for giving my small project an attention :)
*/


DROP TABLE TRAIN CASCADE CONSTRAINTS 
;

DROP TABLE TRAIN_STATION CASCADE CONSTRAINTS 
;

DROP TABLE TRAIN_VOLUME CASCADE CONSTRAINTS 
;

DROP TABLE URA CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE TRAIN 
    ( 
     train_code            VARCHAR2 (4)  NOT NULL , 
     train_name            VARCHAR2 (50)  NOT NULL , 
     train_line_name       VARCHAR2 (50)  NOT NULL , 
     train_start_operation DATE  NOT NULL , 
     train_station_address VARCHAR2 (200)  NOT NULL 
    ) 
;

ALTER TABLE TRAIN 
    ADD 
    CHECK (train_line_name IN ('Bukit Panjang LRT', 'Circle Line', 'Circle Line Extension',  'Changi Airport Branch Line', 'Downtown Line', 'East-West Line', 'North East Line', 'North-South Line', 'Punggol LRT', 'Sengkang LRT', 'Thomson-East Coast Line')) 
;

COMMENT ON COLUMN TRAIN.train_code IS 'train code' 
;

COMMENT ON COLUMN TRAIN.train_name IS 'train name' 
;

COMMENT ON COLUMN TRAIN.train_line_name IS 'train line name' 
;

COMMENT ON COLUMN TRAIN.train_start_operation IS 'train starting operation ' 
;

COMMENT ON COLUMN TRAIN.train_station_address IS 'train station address' 
;

ALTER TABLE TRAIN 
    ADD CONSTRAINT TRAIN_PK PRIMARY KEY ( train_code ) ;

CREATE TABLE TRAIN_STATION 
    ( 
     train_station_address VARCHAR2 (200)  NOT NULL , 
     train_station_lat     NUMBER (10,9)  NOT NULL , 
     train_station_long    NUMBER (10,7)  NOT NULL , 
     ura_area              VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRAIN_STATION.train_station_address IS 'train station address' 
;

COMMENT ON COLUMN TRAIN_STATION.train_station_lat IS 'train station latitude' 
;

COMMENT ON COLUMN TRAIN_STATION.train_station_long IS 'train station longitude' 
;

COMMENT ON COLUMN TRAIN_STATION.ura_area IS 'ura planning area' 
;

ALTER TABLE TRAIN_STATION 
    ADD CONSTRAINT TRAIN_STATION_PK PRIMARY KEY ( train_station_address ) ;

ALTER TABLE TRAIN_STATION 
    ADD CONSTRAINT TRAIN_STATION_UQ UNIQUE ( train_station_lat, train_station_long ) ;

CREATE TABLE TRAIN_VOLUME 
    ( 
     train_volume_id      NUMBER (7)  NOT NULL , 
     train_volume_year_month    DATE  NOT NULL , 
     train_volume_day     VARCHAR2 (50)  NOT NULL , 
     train_volume_hour    NUMBER (2)  NOT NULL , 
     train_code           VARCHAR2 (4)  NOT NULL , 
     train_volume_tap_in  NUMBER (10)  NOT NULL , 
     train_volume_tap_out NUMBER (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_id IS 'train passenger volume id (surrogate PK)' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_year_month IS 'train passenger volume year-month' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_day IS 'train passenger volume day (weekday/weekend/PH)' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_hour IS 'train passenger volume time in hour' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_code IS 'train code' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_tap_in IS 'train passenger volume tap in ' 
;

COMMENT ON COLUMN TRAIN_VOLUME.train_volume_tap_out IS 'train volume passenger volume tap out' 
;

ALTER TABLE TRAIN_VOLUME 
    ADD CONSTRAINT TRAIN_VOLUME_PK PRIMARY KEY ( train_volume_id ) ;

ALTER TABLE TRAIN_VOLUME 
    ADD CONSTRAINT "TRAIN_VOLUME.NK" UNIQUE ( train_volume_year_month, train_volume_hour , train_volume_day , train_code ) ;

CREATE TABLE URA 
    ( 
     ura_area   VARCHAR2 (50)  NOT NULL , 
     ura_region VARCHAR2 (100)  NOT NULL 
    ) 
;

ALTER TABLE URA 
    ADD 
    CHECK (ura_region IN ('CENTRAL REGION', 'EAST REGION', 'NORTH REGION', 'NORTH-EAST REGION', 'WEST REGION')) 
;

COMMENT ON COLUMN URA.ura_area IS 'ura planning area' 
;

COMMENT ON COLUMN URA.ura_region IS 'ura region' 
;

ALTER TABLE URA 
    ADD CONSTRAINT URA_PK PRIMARY KEY ( ura_area ) ;

ALTER TABLE TRAIN_VOLUME 
    ADD CONSTRAINT Relation_4 FOREIGN KEY 
    ( 
     train_code
    ) 
    REFERENCES TRAIN 
    ( 
     train_code
    ) 
;

ALTER TABLE TRAIN 
    ADD CONSTRAINT train_station_train_fk FOREIGN KEY 
    ( 
     train_station_address
    ) 
    REFERENCES TRAIN_STATION 
    ( 
     train_station_address
    ) 
;

ALTER TABLE TRAIN_STATION 
    ADD CONSTRAINT ura_train_station_fk FOREIGN KEY 
    ( 
     ura_area
    ) 
    REFERENCES URA 
    ( 
     ura_area
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
